### PR TITLE
Ritick/projects

### PR DESCRIPTION
**Pull request by ritsiiitd**

### CODE REVIEW

**Comment by aryanteng** [comment]
Screenshot 2024-03-09 at 12 38 32 AM
we can rethink some elements of this design, you can show funded by in some better manner, even the total sanction amount can be shown in a better way, maybe the amount can be shown as a Chip, what do you think about this?

**Comment by ritsiiitd** [comment]
> Screenshot 2024-03-09 at 12 38 32 AM we can rethink some elements of this design, you can show funded by in some better manner, even the total sanction amount can be shown in a better way, maybe the amount can be shown as a Chip, what do you think about this?

image


Now?

**Comment by aryanteng** [comment]
i've described the design changes to you on WhatsApp, please have a look.

**Comment by ritsiiitd** [comment]
> i've described the design changes to you on WhatsApp, please have a look.

image

Final design

**Review by aryanteng — APPROVED** [review]
I have done code fixing and build issue is resolved now.

**Pull request merged**
